version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-176-34-105-15.eu-west-1.compute.amazonaws.com
            port: '5432'
            database: d73kcai9agrgnd
            ssl: true
            user: eibesgopnnbzpv
            password: aaed901dc91c38afd16b149f6cd34ed6746c13fca3caaef0ee8fffb922bfddf9
            migrations: true